name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  ci:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install golangci-lint
        if: matrix.os == 'ubuntu-latest'
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5

      - name: Run golangci-lint
        if: matrix.os == 'ubuntu-latest'
        env:
          CGO_ENABLED: "0"
          GOOS: windows
          GOARCH: amd64
        run: golangci-lint run

      - name: go vet
        env:
          CGO_ENABLED: "0"
          GOOS: windows
          GOARCH: amd64
        run: go vet ./...

      - name: Build (windows/amd64)
        env:
          CGO_ENABLED: "0"
          GOOS: windows
          GOARCH: amd64
        run: go build -trimpath -ldflags="-s -w" ./cmd/wtop/

      - name: Build (windows/arm64)
        env:
          CGO_ENABLED: "0"
          GOOS: windows
          GOARCH: arm64
        run: go build -trimpath -ldflags="-s -w" ./cmd/wtop/

      - name: go test
        run: go test ./...
